### ISSUE TITLE
Cabin temperature messages after engine/battery are off.

### ISSUE THREAD

**Issue by Megaf** [HHS81/c182s#290]
Hi all, so with this model temperature related messages are shown, that is quite alright, tho I do not personally like seeing the messages after I switched off everything and even left the aircraft (for example in walker view).

So my suggestions would be having a checkbox in Aircraft Options to disable the messages.

**Comment by hbeni** [comment]
I think that with fog and frost disabled the messages are hidden too.
Also they should only show when going back inside.

Can you please recheck the above?
If persists, which messages exactly (the red ones?)

**Comment by hbeni** [comment]
@Megaf

**Comment by Megaf** [comment]
These images were taken in sequence, one after another, interval between messages sometimes is less than 5 seconds! And sometimes we get 2 messages at the same time, I find that extremely distracting! (Aircraft started with engine running, live weather at PHNL).
(I **think** they stopped after disabling for and frost, tho I do want fog and frost for realism, I just dont want the messages distracting me)
(I have a couple of neurological things that make the messages specially distracting, maybe for a normal person is ok? I don't know!)

![fgfs-screen-027](https://user-images.githubusercontent.com/6201512/45003299-f3a0d280-afd8-11e8-9c54-bea25b01de5b.png)
![fgfs-screen-028](https://user-images.githubusercontent.com/6201512/45003302-f7ccf000-afd8-11e8-82c9-61b4ae6b8add.png)
![fgfs-screen-029](https://user-images.githubusercontent.com/6201512/45003303-f996b380-afd8-11e8-9c04-8cae5bed7908.png)
![fgfs-screen-030](https://user-images.githubusercontent.com/6201512/45003304-fb607700-afd8-11e8-8cd3-add98536a078.png)
![fgfs-screen-031](https://user-images.githubusercontent.com/6201512/45003305-fd2a3a80-afd8-11e8-970e-9a064b19253c.png)
![fgfs-screen-032](https://user-images.githubusercontent.com/6201512/45003306-00bdc180-afd9-11e8-98ef-35f8db8f0184.png)
![fgfs-screen-033](https://user-images.githubusercontent.com/6201512/45003309-04e9df00-afd9-11e8-9081-244dbdc6f1f1.png)
![fgfs-screen-034](https://user-images.githubusercontent.com/6201512/45003311-087d6600-afd9-11e8-83ee-152e3507a091.png)
![fgfs-screen-035](https://user-images.githubusercontent.com/6201512/45003313-0c10ed00-afd9-11e8-8212-374f5edac97b.png)
![fgfs-screen-036](https://user-images.githubusercontent.com/6201512/45003314-0f0bdd80-afd9-11e8-8fe9-32c736363afb.png)

**Comment by hbeni** [comment]
Okay, thank you very much for those elaborate screens!

The intended behavior is to show such a message:
1) every time you enter the plane (switch view to cockpit)
2) every time the state changes (for example, when the temperature gets warmer and leavesmhe "OK"-range)
3) every 60 seconds, if he temp is way too cold or way to hot (the red text messages)

I will add a property so you can comfortably disable the messages!

**Comment by hbeni** [comment]
Should be fixed in the branch `Issue290`

**Comment by Megaf** [comment]
@hbeni I like that, thanks.
We still have the frost happening but without any message distracting me.

Thank you, and I like the way you offered the option that dialog box.

**Comment by hbeni** [comment]
Thanks for reporting 😀
